# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.109:3306/authorize_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong&useSSL=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2021@Ymd
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: bit123456
    timeout: 6000
    pool:
      max-active: 1000
      max-wait: 10000
      max-idle: 10
      min-idle: 5

ymd:
  client:
    api: ymd/api/v1.0.0
  iot:
    # 变动区域
    productId: a1jVus9r5Ub
  gateAuthSync: http://127.0.0.1:7886/gateAuthSync
  mqtt2: http://127.0.0.1:7886/mqtt2


##巨龙中心服务地址   设备连接端口：38023   第三方平台连接端口:3335   测试http://192.168.31.131:3335
JLPushMiddleServer: http://elock.hzbit.com:3335