server:
  port: 9883
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @profiles.active@
  application:
    name: ymd-event-center

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.ymd.cloud.eventCenter.model.vo
  mapper-locations: classpath:mapper/*.xml,mapper/*/*.xml

logging:
  level:
    com.ymd.cloud.eventCenter.mapper: debug