# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.109:3306/event_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong&useSSL=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2021@Ymd
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
  rabbitmq:
    addresses: 192.168.10.109:5672
    username: huang
    password: huang
    virtual-host: jingshan
    publisher-returns: true
    publisher-confirms: true #开启交换机发布确认模式,交换机收到或者未收到消息, 都会调用回调实现类的回调确认方法
    template:
      mandatory: true
    ## 消费端配置
    listener:
      simple:
        concurrency: 1
        ## manual:手动 ack（确认）
        acknowledge-mode: auto
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: bit123456
    timeout: 6000
    pool:
      max-active: 1000
      max-wait: 10000
      max-idle: 10
      min-idle: 5
mqtt:
  url: tcp://127.0.0.1:1883
  username: admin
  password: public
  qos: 1
  keep:
    live: 30
  timeout: 10
  producer:
    clientId: ymd_2023_producer_dev
    defaultTopic:
  consumer:
    clientId: ymd_2023_customer_dev
    defaultTopic:
  THREADPOOL_SIZE: 50
